server:
  port: ${PORT:0}
eureka:
  client:
    serviceUrl:
      defaultZone: http://discUser:discPassword@localhost:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${server.port}:${spring.application.instance_id:${random.value}}
spring:
  cloud:
    config:
      username: configUser
      password: configPassword
  redis:
    host: 192.168.10.100
    port: 6379
management:
  security:
    sessions: never
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: threaddump, heapdump

info:
  email: toudidel@gmail.com
app:
  description: v1.0
fraction-service:
  minimum: 101
  maximum: 199
